### ISSUE TITLE
ModernUI_Text error when compiling with Visual Studio 2017

### ISSUE THREAD

**Issue by grog169** [mrfearless/ModernUI#12]
Error	LNK1104	cannot open file 'masm32.lib'

**Comment by mrfearless** [comment]
Yes, the ModernUI_Text control uses masm32 include and lib files in the experimental extension to the control based on the DrawTextEXT code. Currently small parts are tied into the main control (initializing some memory, structures etc), but the main functionality is still to be connected and tested.
The masm32.lib can be sourced from the masm32 sdk (http://masm32.com/download.htm). As some point I will include the small no of functions that it uses (szCmpI and atol) directly in the DrawTextEXT code, so that the library isnt required. Ill try and rejig the code (add some definition) in the meantime to compile without that experimental stuff and thus not require the masm32 library.

**Comment by grog169** [comment]
Thanks for the info. I have compiled with masm.lib and it works fine.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mrfearless** [comment]
Should work now without the masm32.lib requirement
